/* v3.2 visual learning layer */
(function applyVisualVersion(){
 document.title=document.title.replace('3.1','3.2');
 const version=document.querySelector('.brand small');if(version)version.textContent='3.2';
 const baseReport=window.proReportText;
 if(typeof baseReport==='function')window.proReportText=function(){return baseReport().replace('3.1','3.2')};
})();

function visualRail(active){
 const steps=[['listen','보기'],['choose','개입'],['response','반응'],['adapt','수정']];
 const order=steps.map(x=>x[0]),idx=order.indexOf(active);
 return `<nav class="pro-visual-rail" aria-label="전문가 사고 학습 흐름">${steps.map(([id,label],i)=>`<span class="rail-step ${i<idx?'done':''} ${id===active?'active':''}">${label}</span>`).join('')}</nav>`
}
function escapeRegExp(value){return String(value).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function visualQuote(t,showSignals=false){
 let text=esc(t.quote);
 if(showSignals){
  [...t.keys].sort((a,b)=>b.length-a.length).forEach(key=>{
   const safe=esc(key),re=new RegExp(escapeRegExp(safe),'g');
   text=text.replace(re,`<mark class="signal-key">${safe}</mark>`)
  })
 }
 return text
}
function visualCue(text){return `<div class="cue-line visual-cue"><i class="cue-pulse" aria-hidden="true"></i><span>${text}</span></div>`}
function renderExpertLens(s){const m=currentExpertMeta(s);return `<section class="expert-lens visual-lens"><span class="level-badge">EXPERT THINKING · 답이 아닌 판단 과정</span><h3>전문가는 질문 전에 시야를 세 갈래로 나눕니다.</h3><div class="expert-columns"><div data-no="01" data-label="LOOK"><b>지금 살아 있는 신호</b><p>${m.focus}</p></div><div data-no="02" data-label="HOLD"><b>아직 단정할 수 없는 것</b><p>${m.unknown}</p></div><div data-no="03" data-label="CHOOSE"><b>가장 적은 개입</b><p>${m.minimal}</p></div></div></section>`}
function impactMeta(c){
 if(c.quality==='strong')return {title:'고객의 탐색이 더 깊어짐',copy:'새로운 의미·감정·정체성 언어가 나타났습니다.',index:0};
 if(c.quality==='some')return {title:'대화는 이어지지만 같은 층위에 머묾',copy:'정보나 행동은 늘었지만 핵심 의미는 아직 남아 있습니다.',index:1};
 return {title:'고객의 탐색 폭이 좁아짐',copy:'혼란·의존·방어가 생기며 코치의 방향이 앞설 수 있습니다.',index:2}
}
function renderImpactMap(c){const m=impactMeta(c),labels=['더 깊어짐','같은 층위','좁아짐'];return `<section class="impact-map ${c.quality}" aria-label="고객 반응 변화"><div><strong>${m.title}</strong><span>${m.copy}</span></div><div class="impact-track" aria-hidden="true">${labels.map((_,i)=>`<i class="${i===m.index?'active':''}"></i>`).join('')}</div><div class="impact-labels">${labels.map((x,i)=>`<b class="${i===m.index?'active':''}">${x}</b>`).join('')}</div></section>`}
function renderAttemptTrail(attempts,current){const all=[...attempts.map(x=>({...x,current:false})),{type:current.type,reaction:current.reaction,quality:current.quality,current:true}];return `<section class="visual-attempts"><header><b>되감기 학습 궤적</b><span>문장이 아니라 고객 반응의 변화를 비교합니다.</span></header><div class="attempt-timeline visual-trail">${all.map((a,i)=>`<div class="attempt-node ${a.current?'current':''}"><span class="attempt-index">${i+1}</span><b>${a.current?'현재 시도':'이전 시도'} · ${a.type}</b><span>${a.reaction}</span></div>`).join('')}</div></section>`}
function renderSelectedEvidence(t){return `<div class="selected-evidence"><b>따라간 고객 언어</b><span>“${esc(state.pro.selectedKey||t.keys[0])}”</span></div>`}
function renderProObservation(s){const t=s.turns[state.pro.turn],m=currentExpertMeta(s),guide=state.pro.level==='guide';proHeader('전문가의 눈으로 듣기');const opts=shuffle(m.signals.map((x,i)=>({...x,idx:i})));$('#proContent').innerHTML=proSceneCard(s)+visualRail('listen')+`<article class="card"><span class="level-badge">${proLevelName(state.pro.level)}</span><div class="client-bubble visual-client"><span class="speaker">CLIENT</span>${visualQuote(t,guide)}${visualCue(guide?t.cue:'고객의 말과 변화에서 직접 단서를 찾아보세요.')}</div><div class="stage-head"><span class="stage-no">${state.pro.turn+3}</span><h3>고객에게서 실제로 확인한 신호를 고르세요.<small>의도와 원인을 추측하기 전에, 고객이 말하거나 보여준 것에 머뭅니다. 2개 이상 선택하세요.</small></h3></div><div class="signal-lab">${opts.map(o=>`<div class="signal-option ${guide?'guide':''} ${o.kind==='inference'?'inference':''}"><input type="checkbox" name="proSignal" id="proSig_${o.idx}" value="${o.idx}"><label for="proSig_${o.idx}">${o.text}</label></div>`).join('')}</div><div class="stage" style="margin-top:20px"><div class="stage-head"><span class="stage-no">↺</span><h3>이 말을 듣는 내 안에는 무엇이 먼저 일어나나요?<small>전문가는 고객뿐 아니라 자신의 조급함과 불편함도 함께 봅니다.</small></h3></div><div class="coach-reaction-grid">${coachInnerReactions.map((r,i)=>`<div class="coach-reaction"><input type="radio" name="proInner" id="proInner_${i}" value="${r.id}"><label for="proInner_${i}">${r.text}</label></div>`).join('')}</div></div><div class="actions"><button class="btn primary" id="proObserveContinue" disabled>${state.pro.level==='solo'?'내 관찰로 개입 선택':'전문가의 시야와 비교'}</button></div></article>`;const validate=()=>{$('#proObserveContinue').disabled=$$('input[name=proSignal]:checked').length<2||!$('input[name=proInner]:checked')};$$('input[name=proSignal],input[name=proInner]').forEach(x=>x.addEventListener('change',validate));$('#proObserveContinue').addEventListener('click',()=>{const chosen=$$('input[name=proSignal]:checked').map(x=>m.signals[Number(x.value)]),inner=$('input[name=proInner]:checked').value,key=turnKey(s);state.pro.observations[key]={signals:chosen,inner};state.pro.learning.observe++;if(chosen.some(x=>x.kind==='inference')){}else state.pro.learning.separate++;state.pro.turnStage='choose';save();renderPro()})}
function renderProChoice(s){const t=s.turns[state.pro.turn],obs=state.pro.observations[turnKey(s)]||{signals:[],inner:''},showLens=state.pro.level!=='solo';const ints=interventionOptions(s,t);proHeader('가장 작은 개입 시험하기');$('#proContent').innerHTML=proSceneCard(s)+visualRail('choose')+`<article class="card"><span class="level-badge">${proLevelName(state.pro.level)}</span><div class="client-bubble visual-client"><span class="speaker">CLIENT</span>${visualQuote(t,state.pro.level==='guide')}${visualCue(t.cue)}</div><div class="observation-summary">${obs.signals.map(x=>`<span>${x.text}</span>`).join('')}<span>내 반응 · ${coachInnerReactions.find(r=>r.id===obs.inner)?.text||''}</span></div>${showLens?renderExpertLens(s):`<div class="notice"><b>SOLO 모드</b><br>전문가의 사고과정은 고객 반응을 확인한 뒤 공개됩니다.</div>`}<div class="stage-head"><span class="stage-no">${state.pro.turn+3}</span><h3>지금 고객에게 필요한 가장 작은 개입은 무엇인가요?<small>멋진 질문보다 고객이 스스로 더 움직일 수 있는 만큼만 개입합니다.</small></h3></div><div class="listen-chips">${t.keys.map((k,i)=>`<div class="listen-chip"><input type="radio" name="proKey" id="proKey_${i}" value="${esc(k)}"><label for="proKey_${i}">“${esc(k)}”</label></div>`).join('')}</div><fieldset><legend class="micro">질문·반영·관찰·침묵 중 하나</legend><div class="intervention-list">${ints.map((o,i)=>`<div class="intervention ${o.id==='minimal_extra'?'minimal':''}"><input type="radio" name="proInterventionV31" id="proIntV31_${i}" value="${i}"><label for="proIntV31_${i}"><b>${o.type}</b><span>${o.text}<small class="intervention-note">한 번에 하나의 개입으로 고객 반응을 확인합니다.</small></span></label></div>`).join('')}</div></fieldset><div class="actions"><button class="btn secondary" id="proBackObserve">다시 듣기</button><button class="btn primary" id="proInterventionCheckV31" disabled>고객 반응으로 배워보기</button></div></article>`;const validate=()=>$('#proInterventionCheckV31').disabled=!($('input[name=proKey]:checked')&&$('input[name=proInterventionV31]:checked'));$$('input[name=proKey],input[name=proInterventionV31]').forEach(x=>x.addEventListener('change',validate));$('#proBackObserve').addEventListener('click',()=>{state.pro.turnStage='observe';save();renderPro()});$('#proInterventionCheckV31').addEventListener('click',()=>{const i=Number($('input[name=proInterventionV31]:checked').value),choice=ints[i],key=$('input[name=proKey]:checked').value;state.pro.selectedChoice=choice;state.pro.selectedKey=key;state.pro.phase='reaction';if(choice.id==='minimal_extra'||choice.type.includes('침묵')||choice.type.includes('반영'))state.pro.learning.minimal++;save();renderPro()})}
function recordAttempt(s,c,continued){const key=turnKey(s);state.pro.attemptLog=state.pro.attemptLog||[];state.pro.attemptLog.push({key,scene:s.title,turn:state.pro.turn,type:c.type,text:c.text,reaction:c.reaction,quality:c.quality,continued,at:new Date().toISOString()})}
function renderProReaction(s){const c=state.pro.selectedChoice,t=s.turns[state.pro.turn],showLens=state.pro.level==='solo';proHeader('고객 반응으로 배우기');const attempts=(state.pro.attemptLog||[]).filter(a=>a.key===turnKey(s));const activeRail=state.pro.rewinds>0?'adapt':'response';$('#proContent').innerHTML=proSceneCard(s)+visualRail(activeRail)+`<article class="card reaction-card">${renderSelectedEvidence(t)}<div class="response-flow ${c.quality}"><div class="coach-bubble"><span class="speaker">내가 시험한 개입 · ${c.type}</span>${c.text}</div><div class="flow-connector" aria-hidden="true"><span>개입의 영향</span><div class="flow-line"><i class="flow-dot"></i></div><span class="flow-arrow">→</span></div><div class="client-bubble visual-client"><span class="speaker">고객의 다음 반응</span>${c.reaction}</div></div>${renderImpactMap(c)}${showLens?renderExpertLens(s):''}<div class="reaction-reading"><div><b>고객 반응에서 새롭게 보이는 것</b><p>${reactionSignal(c)}</p></div><div><b>전문가의 복기</b><p>${c.observe} ${c.impact}</p></div></div><div class="pro-learning"><div><b>내 개입이 한 일</b><p>${c.observe}</p></div><div><b>놓칠 수 있는 것</b><p>${c.impact}</p></div><div><b>더 작게 또는 다르게</b><p>${c.alternative}</p></div></div><div class="reflection-prompt"><b>정답 대신 이 질문으로 복기합니다.</b><p>고객은 자기 언어로 더 깊어졌나요, 코치의 방향에 맞추었나요? 방금 개입을 유지할 근거와 바꿀 근거는 무엇인가요?</p></div>${renderAttemptTrail(attempts,c)}<div class="rewind-box"><span>되감기는 오답 수정이 아니라 고객 반응을 근거로 코치 자신을 수정하는 연습입니다.</span><b>재시도 ${state.pro.rewinds}회</b></div><div class="actions"><button class="btn secondary" id="proRewindV31">고객 반응을 보고 다시 개입하기</button><button class="btn primary" id="proContinueV31">이 반응을 따라 계속하기</button></div></article>`;$('#proRewindV31').addEventListener('click',()=>{recordAttempt(s,c,false);state.pro.rewinds++;state.pro.learning.adapt++;state.pro.turnStage='choose';state.pro.phase='turn';save();renderPro()});$('#proContinueV31').addEventListener('click',()=>{recordAttempt(s,c,true);state.pro.turn++;state.pro.turnStage='observe';state.pro.selectedChoice=null;if(state.pro.turn<s.turns.length)state.pro.phase='turn';else state.pro.phase='action';save();renderPro()})}
