window.VALUE_SCENE_DATA = {
  categories: [
    { id: 'self', label: 'ME', title: '나답게', description: '내 안의 기준과 감각' },
    { id: 'people', label: 'WITH', title: '사람과', description: '관계와 연결의 방식' },
    { id: 'growth', label: 'MOVE', title: '움직이며', description: '일과 성장의 추진력' },
    { id: 'rhythm', label: 'LIFE', title: '살아가며', description: '삶의 리듬과 방향' }
  ],
  values: [
    { name:'가족', note:'가까운 사람을 삶의 중심에 두는 마음', category:'people' },
    { name:'감사', note:'이미 있는 좋은 것을 알아보는 시선', category:'self' },
    { name:'건강', note:'몸과 마음의 컨디션을 지키는 일', category:'rhythm' },
    { name:'겸손', note:'나만 맞다고 세우지 않는 태도', category:'self' },
    { name:'공감', note:'상대의 입장에서 한 번 더 느껴보는 마음', category:'people' },
    { name:'공정', note:'누구에게나 납득되는 기준을 지키는 것', category:'people' },
    { name:'관계', note:'혼자보다 함께 만드는 삶을 중요하게 여김', category:'people' },
    { name:'균형', note:'한쪽에 다 쓰지 않고 리듬을 맞추는 감각', category:'rhythm' },
    { name:'기쁨', note:'마음이 환해지는 순간을 놓치지 않는 것', category:'self' },
    { name:'끈기', note:'잘 안돼도 다시 붙잡고 이어가는 힘', category:'growth' },
    { name:'나눔', note:'내가 가진 것을 기꺼이 건네는 마음', category:'people' },
    { name:'도전', note:'익숙한 선을 넘어 한 번 해보는 용기', category:'growth' },
    { name:'독립', note:'내 힘으로 서고 선택하는 감각', category:'self' },
    { name:'명료함', note:'복잡한 것에서 핵심을 또렷하게 잡는 것', category:'self' },
    { name:'몰입', note:'한 가지에 깊이 빠져드는 시간', category:'growth' },
    { name:'배려', note:'상대가 편할 자리를 먼저 살피는 마음', category:'people' },
    { name:'배움', note:'모르는 것을 새롭게 알아가는 즐거움', category:'growth' },
    { name:'변화', note:'지금과 다른 가능성을 열어두는 태도', category:'growth' },
    { name:'봉사', note:'필요한 곳에 내 시간과 힘을 보태는 일', category:'people' },
    { name:'사랑', note:'소중한 존재를 아끼고 표현하는 마음', category:'people' },
    { name:'성실', note:'눈에 띄지 않아도 꾸준히 해내는 태도', category:'growth' },
    { name:'성장', note:'어제보다 조금씩 나아지고 싶은 마음', category:'growth' },
    { name:'소속', note:'여기에 내가 함께 있다는 안정감', category:'people' },
    { name:'신뢰', note:'서로를 믿고 맡길 수 있는 관계', category:'people' },
    { name:'안정', note:'쉽게 흔들리지 않는 바닥을 만드는 것', category:'rhythm' },
    { name:'여유', note:'급하게 몰지 않고 숨 쉴 틈을 두는 것', category:'self' },
    { name:'연결', note:'사람과 진짜 닿고 있다는 감각', category:'people' },
    { name:'영향력', note:'내 선택으로 주변에 변화를 만드는 힘', category:'growth' },
    { name:'용기', note:'두려워도 필요한 쪽으로 한 발 내딛는 힘', category:'self' },
    { name:'유연함', note:'상황에 맞게 생각과 방식을 바꾸는 감각', category:'rhythm' },
    { name:'의미', note:'왜 하는지 스스로 납득되는 방향', category:'rhythm' },
    { name:'자기존중', note:'나를 함부로 대하지 않는 기준', category:'self' },
    { name:'자율', note:'내 기준으로 선택하고 책임지는 감각', category:'self' },
    { name:'정직', note:'숨기거나 꾸미지 않고 사실대로 마주하는 태도', category:'self' },
    { name:'존재감', note:'눈치 보지 않고 내 자리를 차지하는 감각', category:'self' },
    { name:'즐거움', note:'재미와 웃음이 있는 방식을 선택하는 것', category:'self' },
    { name:'창의성', note:'익숙한 답 말고 새로운 조합을 만드는 힘', category:'growth' },
    { name:'책임감', note:'맡은 것을 끝까지 가져가는 힘', category:'growth' },
    { name:'친밀함', note:'가까운 마음을 솔직하게 나누는 관계', category:'people' },
    { name:'탁월함', note:'대충 넘기지 않고 더 좋은 수준을 만드는 것', category:'growth' },
    { name:'평화', note:'마음과 관계에 불필요한 싸움을 줄이는 것', category:'self' },
    { name:'회복', note:'지친 뒤 다시 내 리듬으로 돌아오는 힘', category:'rhythm' },
    { name:'호기심', note:'모르는 것에 한 번 더 질문해보는 마음', category:'growth' },
    { name:'희망', note:'아직 달라질 수 있다고 보는 시선', category:'rhythm' },
    { name:'확신', note:'내가 고른 방향을 믿고 가는 마음', category:'self' },
    { name:'활력', note:'몸과 마음에 생기가 도는 상태', category:'rhythm' },
    { name:'효율', note:'덜 쓰고도 더 잘되게 만드는 방식', category:'growth' },
    { name:'헌신', note:'중요한 일에 마음과 시간을 깊이 쓰는 것', category:'growth' },
    { name:'개성', note:'남과 다른 나만의 결을 드러내는 것', category:'self' },
    { name:'결단', note:'계속 재지 않고 한쪽을 선택하는 힘', category:'growth' },
    { name:'경청', note:'대답보다 먼저 상대의 말을 끝까지 듣는 태도', category:'people' },
    { name:'공헌', note:'내가 있는 곳을 조금 더 낫게 만드는 일', category:'people' },
    { name:'규칙', note:'흔들릴 때 돌아올 약속을 세우는 것', category:'rhythm' },
    { name:'낙관', note:'가능한 쪽을 먼저 찾아보는 태도', category:'self' },
    { name:'다양성', note:'서로 다른 방식이 함께 있을 자리를 만드는 것', category:'people' },
    { name:'단순함', note:'불필요한 것을 덜어 핵심만 남기는 것', category:'rhythm' },
    { name:'리더십', note:'방향을 세우고 사람의 힘을 모으는 것', category:'growth' },
    { name:'모험', note:'계획 밖의 낯선 경험을 기꺼이 만나는 것', category:'rhythm' },
    { name:'목적', note:'어디로 가는지 분명히 알고 움직이는 것', category:'growth' },
    { name:'성취', note:'정한 것을 실제 결과로 끝내는 기쁨', category:'growth' },
    { name:'세심함', note:'작은 차이와 놓치기 쉬운 부분을 살피는 힘', category:'growth' },
    { name:'속도', note:'기회를 놓치지 않고 빠르게 움직이는 것', category:'growth' },
    { name:'수용', note:'바로 판단하지 않고 있는 그대로 두어보는 태도', category:'self' },
    { name:'실용', note:'현실에서 실제로 쓸모 있는 방식을 고르는 것', category:'growth' },
    { name:'아름다움', note:'보기 좋고 마음이 끌리는 감각을 지키는 것', category:'rhythm' },
    { name:'안전', note:'위험을 줄이고 마음 놓을 환경을 만드는 것', category:'rhythm' },
    { name:'온전함', note:'쪼개지지 않고 나답게 하나로 서는 감각', category:'self' },
    { name:'우정', note:'편하게 기대고 함께 웃을 사람이 있는 삶', category:'people' },
    { name:'유머', note:'무거운 순간에도 웃을 틈을 만드는 힘', category:'self' },
    { name:'인정', note:'서로의 수고와 가치를 알아봐 주는 것', category:'people' },
    { name:'일관성', note:'상황이 달라도 내 기준을 이어가는 태도', category:'rhythm' },
    { name:'자유', note:'내 방식대로 숨 쉬고 선택하는 감각', category:'self' },
    { name:'전문성', note:'내 분야를 믿고 맡길 만큼 깊게 만드는 것', category:'growth' },
    { name:'절제', note:'원하는 대로 다 하지 않고 필요한 만큼 고르는 힘', category:'rhythm' },
    { name:'정돈', note:'흩어진 것에 자리와 순서를 만들어 주는 것', category:'rhythm' },
    { name:'존중', note:'나와 상대의 경계를 가볍게 넘지 않는 태도', category:'people' },
    { name:'진실성', note:'말과 행동이 내 진짜 마음과 맞아 있는 것', category:'self' },
    { name:'집중', note:'지금 중요한 한 가지에 힘을 모으는 것', category:'growth' },
    { name:'협력', note:'각자의 힘을 연결해 함께 해내는 것', category:'people' },
    { name:'현실성', note:'지금 가진 조건에서 가능한 길을 찾는 것', category:'rhythm' },
    { name:'독창성', note:'누군가의 복사본이 아닌 내 방식으로 만드는 것', category:'self' },
    { name:'통찰', note:'겉으로 보이는 일 뒤의 흐름을 알아채는 힘', category:'self' },
    { name:'품격', note:'어떤 순간에도 나를 낮추지 않는 태도', category:'rhythm' },
    { name:'풍요', note:'충분히 누리고 나눌 수 있다는 감각', category:'rhythm' },
    { name:'공동체', note:'함께 살아갈 사람과 자리를 돌보는 마음', category:'people' },
    { name:'자비', note:'실수한 나와 타인에게 한 번 더 부드러운 태도', category:'people' },
    { name:'주도성', note:'기다리기보다 내가 먼저 시작하는 힘', category:'growth' },
    { name:'준비', note:'기회가 왔을 때 움직일 수 있게 미리 갖추는 것', category:'rhythm' },
    { name:'지혜', note:'아는 것을 상황에 맞게 잘 쓰는 힘', category:'rhythm' },
    { name:'충성', note:'쉽게 등을 돌리지 않고 관계와 약속을 지키는 것', category:'people' },
    { name:'투명성', note:'정보와 의도를 숨김없이 나누는 태도', category:'people' },
    { name:'포용', note:'나와 다른 사람도 함께 있을 자리를 내는 것', category:'people' },
    { name:'현재성', note:'지나간 일과 다음 걱정 대신 지금에 머무는 힘', category:'self' },
    { name:'정의', note:'옳지 않은 일에 기준을 세우고 목소리 내는 것', category:'rhythm' },
    { name:'휴식', note:'멈춰도 괜찮다고 허락하는 시간', category:'rhythm' },
    { name:'전환', note:'한 시기를 닫고 다음 장으로 넘어가는 것', category:'rhythm' }
  ],
  frictions: [
    { name:'혼란', label:'머릿속이 복잡함', note:'뭘 먼저 해야 할지 잡히지 않는 때', directions:['명료함','단순함','우선순위'] },
    { name:'불안', label:'괜히 불안함', note:'아직 일어나지 않은 일까지 걱정하는 때', directions:['안정','신뢰','준비'] },
    { name:'압박', label:'계속 쫓기는 느낌', note:'멈추면 안 될 것처럼 몰아붙이는 때', directions:['여유','자율','균형'] },
    { name:'무기력', label:'시동이 안 걸림', note:'해야 하는데 몸과 마음이 움직이지 않는 때', directions:['활력','작은 성취','회복'] },
    { name:'고립', label:'혼자 떨어진 느낌', note:'사람들 사이에서도 연결되지 않는 때', directions:['연결','소속','친밀함'] },
    { name:'회피', label:'자꾸 미루고 피함', note:'마주하기보다 다른 일로 빠지는 때', directions:['용기','직면','정직'] },
    { name:'과도한 책임감', label:'다 내가 해야 할 것 같음', note:'도움을 청하거나 나누기 어려운 때', directions:['경계','분담','자기돌봄'] },
    { name:'완벽주의', label:'완벽해야 시작함', note:'잘해야 한다는 마음 때문에 첫발이 늦는 때', directions:['충분함','실험','유연함'] },
    { name:'인정 갈망', label:'인정받아야 안심됨', note:'내 기준보다 다른 사람의 반응이 더 커지는 때', directions:['자기존중','진실성','내적 확신'] },
    { name:'비교', label:'남의 속도만 보임', note:'내 리듬보다 타인의 결과에 시선이 붙는 때', directions:['개성','감사','자기속도'] },
    { name:'분노', label:'자꾸 욱함', note:'참았던 감정이 순간적으로 튀어나오는 때', directions:['존중','공정','표현'] },
    { name:'서운함', label:'마음에 계속 남음', note:'말하지 못한 기대가 오래 걸리는 때', directions:['이해','대화','친밀함'] },
    { name:'통제', label:'내 뜻대로 돼야 편함', note:'예상 밖의 상황을 견디기 어려운 때', directions:['신뢰','협력','수용'] },
    { name:'산만함', label:'집중이 자꾸 끊김', note:'생각과 일이 여기저기로 튀는 때', directions:['집중','정돈','몰입'] },
    { name:'지침', label:'완전히 방전됨', note:'쉬어도 에너지가 잘 돌아오지 않는 때', directions:['휴식','회복','경계'] },
    { name:'두려움', label:'겁부터 남', note:'가능성보다 실패 장면이 먼저 보이는 때', directions:['안전','용기','지원'] },
    { name:'답답함', label:'숨이 막히고 답답함', note:'내 방식과 감정을 꺼내기 어려운 때', directions:['자유','표현','변화'] },
    { name:'무가치감', label:'내가 작아지는 느낌', note:'내가 한 일과 존재를 낮춰 보는 때', directions:['존재감','자기존중','의미'] },
    { name:'죄책감', label:'마음의 빚처럼 남음', note:'지나간 선택을 계속 벌주는 때', directions:['책임감','용서','회복'] },
    { name:'관계 긴장', label:'말 한마디도 조심스러움', note:'상대 반응을 살피느라 나를 잃는 때', directions:['경청','존중','명료함'] },
    { name:'결정 미룸', label:'결정을 계속 넘김', note:'선택의 결과가 부담스러워 멈춰 있는 때', directions:['결단','기준','작은 행동'] },
    { name:'방향 상실', label:'어디로 갈지 모르겠음', note:'해야 할 일은 많은데 이유가 흐린 때', directions:['목적','호기심','탐색'] },
    { name:'과부하', label:'할 일이 한꺼번에 몰림', note:'중요한 것과 급한 것이 뒤엉킨 때', directions:['우선순위','단순함','분담'] },
    { name:'냉소', label:'해봤자라는 마음', note:'기대하기보다 먼저 포기하고 싶은 때', directions:['희망','의미','참여'] },
    { name:'외로움', label:'사람 속에서도 외로움', note:'마음을 나눌 곳이 없다고 느끼는 때', directions:['연결','우정','공동체'] },
    { name:'무시당함', label:'존중받지 못한 느낌', note:'내 말과 경계가 가볍게 다뤄진 때', directions:['존중','표현','경계'] },
    { name:'조급함', label:'빨리 결론내고 싶음', note:'과정을 건너뛰고 결과를 당기고 싶은 때', directions:['현재성','인내','자기속도'] },
    { name:'정체감 혼란', label:'내가 누군지 흔들림', note:'역할과 기대 사이에서 내 목소리가 흐린 때', directions:['개성','진실성','자기이해'] },
    { name:'실패 두려움', label:'틀리면 끝일 것 같음', note:'시도보다 실패 뒤의 시선이 먼저 보이는 때', directions:['실험','배움','도전'] },
    { name:'갈등 회피', label:'부딪히기 싫어 침묵함', note:'관계를 지키려다 필요한 말을 삼키는 때', directions:['대화','용기','협력'] }
  ],
  contexts: [
    { id:'whole', title:'삶 전체', icon:'WIDE', description:'지금의 나를 넓게 펼쳐서 봅니다.' },
    { id:'work', title:'일과 역할', icon:'WORK', description:'일, 사업, 리더십 장면을 중심에 둡니다.' },
    { id:'relationship', title:'사람과 관계', icon:'WITH', description:'가족, 동료, 친구 사이를 살펴봅니다.' },
    { id:'transition', title:'다음 장면', icon:'NEXT', description:'이직, 진로, 새로운 시작을 바라봅니다.' }
  ],
  coachPrompts: {
    1:'정의를 설명하기 전에 반응을 기다려 주세요. “왜 좋은 단어인가요?”보다 “왜 지금 이 단어가 먼저 들어왔나요?”가 좋습니다.',
    2:'모두 중요하다는 말이 나오면 “이번 계절의 나에게 덜 필요한 것은 무엇인가요?”라고 물어 덜어내기를 돕습니다.',
    3:'끝까지 남은 말뿐 아니라 마지막까지 덜어내기 어려웠던 말을 함께 관찰해 보세요.',
    4:'걸리는 경험을 없앨 대상으로 다루지 않습니다. 그 경험이 지키려는 것과 필요한 방향을 발견하도록 돕습니다.',
    5:'원하는 방향을 곧바로 목표로 만들지 말고, 그 방향이 절실해진 실제 순간을 먼저 떠올리게 합니다.',
    6:'해석보다 카메라로 찍힐 법한 장면을 요청하세요. 언제, 어디서, 누구와, 무슨 말이 오갔는지가 선명도를 높입니다.',
    7:'두 가치 중 하나를 버리게 하지 않습니다. 둘을 함께 존중할 수 있는 순서, 경계, 제3의 선택을 탐색합니다.',
    8:'다짐은 보이는 행동으로 번역합니다. 실행 여부를 스스로 확인할 수 있을 만큼 작고 구체적으로 만듭니다.'
  }
};
