(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const STORE='cfm-v4-live-response-return';
const CAPTURE_STORE='cfm-v4-3sec-capture-log';
let queued=false;
function readJSON(key,fallback=null){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function writeJSON(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function activeId(){try{const id=sessionStorage.getItem('cfm-v4-active-capture-live');if(id)return id;const made=`live-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;sessionStorage.setItem('cfm-v4-active-capture-live',made);return made}catch{return 'live-current'}}
function allRecords(){const v=readJSON(STORE,{});return v&&typeof v==='object'?v:{}}
function captureText(id){const log=readJSON(CAPTURE_STORE,[]);const hit=Array.isArray(log)?log.find(x=>x?.id===id):null;return String(hit?.text||'')}
function record(){const all=allRecords(),id=activeId();return all[id]||{id,start:5,end:5,endTouched:false,note:'',updatedAt:null}}
function save(patch){const all=allRecords(),id=activeId(),prev=all[id]||record();all[id]={...prev,...patch,id,updatedAt:new Date().toISOString()};writeJSON(STORE,all);window.dispatchEvent(new CustomEvent('cfm:live-return-updated',{detail:all[id]}));return all[id]}
function deltaLabel(start,end){const d=end-start;if(d<0)return `${Math.abs(d)}만큼 낮아짐`;if(d>0)return `${d}만큼 높아짐`;return '변화 없음'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function buildStart(){const r=record(),el=document.createElement('label');el.className='cfm-live-start-check';el.dataset.liveReturn='start';el.innerHTML=`<span>지금 코치 안에서 일어나는 긴장·조급함·확신의 정도</span><input type="range" min="1" max="10" step="1" value="${r.start}"><div><span>1 · 낮음</span><output>${r.start}</output><span>10 · 매우 강함</span></div>`;const range=$('input',el),out=$('output',el);range.addEventListener('input',()=>{out.textContent=range.value;const current=record();save({start:Number(range.value),end:current.endTouched?current.end:Number(range.value)})});return el}
function buildEditor(){const r=record(),first=captureText(r.id),el=document.createElement('aside');el.className='cfm-emotion-check cfm-live-return';el.dataset.liveReturn='editor';el.innerHTML=`<div class="cfm-emotion-title"><span>COACH RESPONSE · CHECK AGAIN</span><strong>코치의 반응을 다시 확인합니다.</strong></div><p class="cfm-emotion-copy">고객이 달라졌는지만 보지 않고, 같은 장면을 지금 코치가 어떻게 다르게 보고 있는지 알아차립니다.</p>${first?`<div class="cfm-live-first"><b>처음 3초 안에 떠오른 반응</b>\n${esc(first)}</div>`:''}<div class="cfm-emotion-numbers"><div><small>시작</small><b>${r.start}</b><em>/10</em></div><i>→</i><div><small>지금</small><b data-end>${r.end}</b><em>/10</em></div><div class="cfm-emotion-change"><small>변화</small><b data-delta>${esc(deltaLabel(r.start,r.end))}</b></div></div><label class="cfm-emotion-range"><span>지금 코치 안에서 일어나는 긴장·조급함·확신의 정도</span><input type="range" min="1" max="10" step="1" value="${r.end}"><div><span>1 · 낮음</span><output>${r.end}</output><span>10 · 매우 강함</span></div></label><label class="cfm-emotion-awareness"><span>처음의 코치와 지금의 코치는 무엇을 다르게 보고 있나요?</span><textarea maxlength="700" placeholder="고객에게 기대했던 반응, 처음 하려던 개입, 새롭게 보인 고객의 언어나 다음 선택을 적어보세요.">${esc(r.note)}</textarea></label><p class="cfm-emotion-status">반응이 낮아지는 것만이 목표는 아닙니다. 내 개입을 만든 규칙이 어떻게 움직였는지 살펴보세요.</p>`;
 const range=$('input[type=range]',el),out=$('output',el),end=$('[data-end]',el),delta=$('[data-delta]',el),note=$('textarea',el),status=$('.cfm-emotion-status',el);let timer=0;const commit=()=>save({end:Number(range.value),endTouched:true,note:note.value});range.addEventListener('input',()=>{out.textContent=range.value;end.textContent=range.value;delta.textContent=deltaLabel(r.start,Number(range.value));clearTimeout(timer);timer=setTimeout(commit,120);status.textContent='수치보다, 고객과 개입을 바라보는 관점이 어떻게 달라졌는지 확인하세요.'});note.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(commit,180);el.classList.toggle('has-note',Boolean(note.value.trim()));status.textContent=note.value.trim()?'코치의 변화가 기록되었습니다. 처음의 반응과 지금의 선택을 함께 볼 수 있습니다.':'반응이 낮아지는 것만이 목표는 아닙니다. 내 개입을 만든 규칙이 어떻게 움직였는지 살펴보세요.'});note.addEventListener('blur',commit);el.classList.toggle('has-note',Boolean(r.note.trim()));return el}
function buildSummary(){const r=record(),first=captureText(r.id),el=document.createElement('article');el.className='cfm-emotion-summary cfm-live-summary';el.dataset.liveReturn='summary';el.innerHTML=`<span>코치 반응의 변화</span><h3>${r.start}/10 → ${r.end}/10</h3><p><b>${esc(deltaLabel(r.start,r.end))}</b>${first?`\n\n처음 반응: ${esc(first)}`:''}\n\n${esc(r.note||'아직 알아차림을 기록하지 않았습니다.')}</p>`;return el}
function finalRoot(){const final=$('#proFinal.active,#liveFinal.active,#professionalFinal.active,[id*="proFinal"].active,[id*="liveFinal"].active');if(!final)return null;return $('#proSummary,#liveSummary,.summary-grid,.result-grid,.results-grid',final)||final}
function endingHost(){const game=$('#proGame.active'),content=$('#proContent');if(!game||!content)return null;const phase=[$('#proPhaseLabel')?.textContent,$('#proRoundLabel')?.textContent,content.textContent].join(' ');if(!/(이중\s*되감기|마무리|최종|통합|회고)/.test(phase))return null;const cards=[...content.querySelectorAll(':scope > article.card')];return cards[cards.length-1]||content}
function inject(){queued=false;const capture=$('.cfm-capture-rhythm[data-mode="live"]');if(capture&&!capture.querySelector('[data-live-return="start"]'))capture.appendChild(buildStart());const end=endingHost(),final=finalRoot();if(end&&!end.querySelector('[data-live-return="editor"]'))end.appendChild(buildEditor());if(final&&!final.querySelector('[data-live-return]')){if(!end||!document.documentElement.contains(end))final.prepend(buildEditor());else final.prepend(buildSummary())}}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(inject)}
window.addEventListener('cfm:capture-created',e=>{if(e.detail?.mode==='live')schedule()});
window.addEventListener('cfm:live-return-updated',schedule);
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();