(()=>{
'use strict';
const CONFIG=window.CFM_SHEETS_CONFIG||{};
if(!CONFIG.enabled||!/^https:\/\/script\.google\.com\//.test(String(CONFIG.endpoint||'')))return;
const SELF_KEY='coaching-flex-move-self-v4';
const LIVE_KEY='coaching-flex-move-live-v4';
const CAPTURE_KEY='cfm-v4-3sec-capture-log';
const SELF_RETURN='cfm-v4-self-emotion-return';
const LIVE_RETURN='cfm-v4-live-response-return';
const SENT_KEY='cfm-v4-sheets-submitted';
const RULES={answer:'고객은 내 질문에 분명하게 답해야 한다.',insight:'고객은 이번 대화에서 통찰을 얻어야 한다.',action:'고객은 실행 의지를 보여야 한다.',understand:'고객은 내 질문의 의도를 이해해야 한다.',goodcoach:'나는 좋은 코치처럼 보여야 한다.',none:'아직 어떤 기대가 작동하는지 모르겠다.'};
let queued=false;
function read(key,fallback=null){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function activeId(mode){try{return sessionStorage.getItem('cfm-v4-active-capture-'+mode)||''}catch{return''}}
function latest(object){const list=Object.values(object&&typeof object==='object'?object:{});return list.sort((a,b)=>String(b?.updatedAt||'').localeCompare(String(a?.updatedAt||'')))[0]||null}
function capture(mode,id){const log=read(CAPTURE_KEY,[]);return Array.isArray(log)?(log.find(x=>x?.id===id)||[...log].reverse().find(x=>x?.mode===mode)||null):null}
function recordFor(key,id){const all=read(key,{});return(all&&all[id])||latest(all)}
function trimText(value,max=700){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function redact(value){return trimText(value).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[이메일 삭제]').replace(/(?:https?:\/\/|www\.)\S+/gi,'[링크 삭제]').replace(/(?:\+?82[-. ]?)?0?1[016789][-. ]?\d{3,4}[-. ]?\d{4}/g,'[연락처 삭제]').replace(/\b\d{6}[- ]?[1-4]\d{6}\b/g,'[식별번호 삭제]')}
function sent(){const value=read(SENT_KEY,{});return value&&typeof value==='object'?value:{}}
function markSent(id){const value=sent();value[id]=new Date().toISOString();try{localStorage.setItem(SENT_KEY,JSON.stringify(value))}catch{}}
function selfPayload(){const state=read(SELF_KEY,null);if(!state?.completed)return null;const id=activeId('self'),ret=recordFor(SELF_RETURN,id),cap=capture('self',id),d=state.data||{};return{id:id||ret?.id||('self-'+Date.now()),mode:'SELF',startedAt:cap?.createdAt||ret?.updatedAt||new Date().toISOString(),endedAt:ret?.updatedAt||new Date().toISOString(),start:Number(d.intensity||ret?.start||0),end:Number(ret?.end||d.intensity||0),emotionChange:d.bodyChange||'',rule:d.rule||'',awareness:ret?.note||'',nextChoice:d.nextAction||''}}
function livePayload(){const state=read(LIVE_KEY,null);if(!state?.completed||!state?.pro?.completed)return null;const id=activeId('live'),ret=recordFor(LIVE_RETURN,id),cap=capture('live',id),obs=Object.values(state.pro.observations||{}),attempts=state.pro.attemptLog||[],lastObs=obs[obs.length-1]||{},lastAttempt=attempts[attempts.length-1]||{};return{id:id||ret?.id||('live-'+Date.now()),mode:'LIVE',startedAt:cap?.createdAt||lastAttempt.at||ret?.updatedAt||new Date().toISOString(),endedAt:ret?.updatedAt||lastAttempt.at||new Date().toISOString(),start:Number(ret?.start||0),end:Number(ret?.end||ret?.start||0),emotionChange:'',rule:RULES[lastObs.rule]||RULES[lastAttempt.innerRule]||'',awareness:ret?.note||'',nextChoice:lastAttempt.text||''}}
function payloadFor(mode){return mode==='SELF'?selfPayload():livePayload()}
function style(){if(document.getElementById('cfmSheetsStyle'))return;const s=document.createElement('style');s.id='cfmSheetsStyle';s.textContent='.cfm-sheet-share{margin:24px 0;padding:20px;border:1px solid rgba(220,255,69,.28);border-radius:18px;background:rgba(220,255,69,.045);color:#f7f4ec}.cfm-sheet-share h3{margin:5px 0 9px;font-size:clamp(20px,4vw,28px)}.cfm-sheet-share p{color:#c9c6be;line-height:1.65}.cfm-sheet-share ul{padding-left:20px;color:#dedbd2;line-height:1.65}.cfm-sheet-share details{margin:14px 0;padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:14px}.cfm-sheet-share label{display:block;margin:10px 0;color:#eee}.cfm-sheet-share textarea{box-sizing:border-box;width:100%;min-height:74px;margin-top:6px;padding:11px;border:1px solid rgba(255,255,255,.18);border-radius:10px;background:#101214;color:#fff;font:inherit;line-height:1.55}.cfm-sheet-consent{display:flex!important;gap:9px;align-items:flex-start}.cfm-sheet-consent input{margin-top:5px}.cfm-sheet-share button{width:100%;padding:13px 16px;border:0;border-radius:12px;background:#dcff45;color:#10110d;font-weight:850;font-size:15px;cursor:pointer}.cfm-sheet-share button:disabled{opacity:.45;cursor:not-allowed}.cfm-sheet-status{min-height:24px;margin:10px 0 0!important;font-size:13px}.cfm-sheet-share.is-done{border-color:rgba(130,230,180,.45)}';document.head.appendChild(s)}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function create(mode,host){const data=payloadFor(mode);if(!data||sent()[data.id])return;const box=document.createElement('section');box.className='cfm-sheet-share';box.dataset.cfmSheetShare=mode;box.innerHTML='<small>ANONYMOUS LEARNING DATA</small><h3>이번 기록을 비식별 학습 데이터로 보낼까요?</h3><p>전송 여부는 선택입니다. 보내지 않아도 모든 기능을 그대로 사용할 수 있습니다.</p><ul><li>전송: 모드, 시작·종료 시각, 시작·종료 강도, 변화, 머릿속 규칙, 알아차림, 다음 선택</li><li>전송하지 않음: 이름, 연락처, 로그인 정보, 장면 속 인물·기관, 기기 식별자</li></ul><details><summary>전송 전 서술 기록 확인·수정</summary><label>머릿속 규칙<textarea data-field="rule" maxlength="700">'+esc(data.rule)+'</textarea></label><label>알아차림<textarea data-field="awareness" maxlength="700">'+esc(data.awareness)+'</textarea></label><label>다음 선택<textarea data-field="nextChoice" maxlength="700">'+esc(data.nextChoice)+'</textarea></label><p>사람 이름, 기관명, 연락처가 있다면 삭제하거나 일반 표현으로 바꿔주세요. 이메일·전화번호·링크는 전송 직전 한 번 더 자동 가림 처리됩니다.</p></details><label class="cfm-sheet-consent"><input type="checkbox"><span>위 항목을 확인했으며, 이 기록의 비식별 통계·연구 활용 전송에 동의합니다.</span></label><button type="button" disabled>비식별 기록 보내기</button><p class="cfm-sheet-status" aria-live="polite"></p>';const consent=box.querySelector('input[type=checkbox]'),button=box.querySelector('button'),status=box.querySelector('.cfm-sheet-status');consent.addEventListener('change',()=>button.disabled=!consent.checked);button.addEventListener('click',async()=>{button.disabled=true;status.textContent='개인정보 표현을 가린 뒤 전송하고 있습니다.';data.rule=redact(box.querySelector('[data-field=rule]').value);data.awareness=redact(box.querySelector('[data-field=awareness]').value);data.nextChoice=redact(box.querySelector('[data-field=nextChoice]').value);data.emotionChange=redact(data.emotionChange);data.schemaVersion=CONFIG.schemaVersion||'1.0';data.source=CONFIG.source||'coaching-flex-move';data.submissionId=(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));try{await fetch(CONFIG.endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(data)});const confirmed=await confirmReceipt(data.submissionId);if(!confirmed)throw new Error('receipt-timeout');markSent(data.id);box.classList.add('is-done');box.innerHTML='<small>TRANSFER COMPLETE</small><h3>비식별 기록이 전송되었습니다.</h3><p>이번 훈련의 원문은 이 브라우저에 남고, 확인한 항목만 집계 시트에 저장되었습니다.</p>'}catch(e){status.textContent='전송을 확인하지 못했습니다. 기록은 브라우저에 그대로 보존됩니다. 잠시 후 다시 시도해 주세요.';button.disabled=!consent.checked;console.error('[CFM sheets]',e)}});host.appendChild(box)}
function confirmReceipt(id){return new Promise(resolve=>{let tries=0,done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const check=()=>{if(++tries>6)return finish(false);const cb='__cfmReceipt'+Date.now()+Math.random().toString(36).slice(2);const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();setTimeout(check,650)},2200);const cleanup=()=>{clearTimeout(timer);delete window[cb];script.remove()};window[cb]=result=>{cleanup();if(result?.found)finish(true);else setTimeout(check,500)};script.onerror=()=>{cleanup();setTimeout(check,650)};script.src=CONFIG.endpoint+'?action=status&submissionId='+encodeURIComponent(id)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(script)};setTimeout(check,500)})}
function inject(){queued=false;style();const self=document.querySelector('#selfFinal.active'),live=document.querySelector('#proFinal.active,#liveFinal.active,#professionalFinal.active');if(self&&!self.querySelector('[data-cfm-sheet-share]'))create('SELF',self.querySelector('#selfSummary')?.parentElement||self);if(live&&!live.querySelector('[data-cfm-sheet-share]'))create('LIVE',live.querySelector('#proSummary,#liveSummary,.summary-grid,.result-grid,.results-grid')?.parentElement||live)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(inject)}
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
