(()=>{
'use strict';
const CONFIG=window.CFM_SHEETS_CONFIG||{};
if(!CONFIG.enabled||!/^https:\/\/script\.google\.com\//.test(String(CONFIG.endpoint||'')))return;
const SELF_KEY='coaching-flex-move-self-v4';
const LIVE_KEY='coaching-flex-move-live-v4';
const CAPTURE_KEY='cfm-v4-3sec-capture-log';
const SELF_RETURN='cfm-v4-self-emotion-return';
const LIVE_RETURN='cfm-v4-live-response-return';
const SENT_KEY='cfm-v4-sheets-submitted';
const RULES={answer:'고객은 내 질문에 분명하게 답해야 한다.',insight:'고객은 이번 대화에서 통찰을 얻어야 한다.',action:'고객은 실행 의지를 보여야 한다.',understand:'고객은 내 질문의 의도를 이해해야 한다.',goodcoach:'나는 좋은 코치처럼 보여야 한다.',none:'아직 어떤 기대가 작동하는지 모르겠다.'};
let queued=false;
function read(key,fallback=null){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function activeId(mode){try{return sessionStorage.getItem('cfm-v4-active-capture-'+mode)||''}catch{return''}}
function latest(object){const list=Object.values(object&&typeof object==='object'?object:{});return list.sort((a,b)=>String(b?.updatedAt||'').localeCompare(String(a?.updatedAt||'')))[0]||null}
function capture(mode,id){const log=read(CAPTURE_KEY,[]);return Array.isArray(log)?(log.find(x=>x?.id===id)||[...log].reverse().find(x=>x?.mode===mode)||null):null}
function recordFor(key,id){const all=read(key,{});return(all&&all[id])||latest(all)}
function trimText(value,max=700){return String(value||'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,max)}
function redact(value){return trimText(value).replace(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,'[이메일 삭제]').replace(/(?:https?:\/\/|www\.)\S+/gi,'[링크 삭제]').replace(/(?:\+?82[-. ]?)?0?1[016789][-. ]?\d{3,4}[-. ]?\d{4}/g,'[연락처 삭제]').replace(/\b\d{6}[- ]?[1-4]\d{6}\b/g,'[식별번호 삭제]')}
function sent(){const value=read(SENT_KEY,{});return value&&typeof value==='object'?value:{}}
function markSent(id){const value=sent();value[id]=new Date().toISOString();try{localStorage.setItem(SENT_KEY,JSON.stringify(value))}catch{}}
function selfPayload(){const state=read(SELF_KEY,null);if(!state?.completed)return null;const id=activeId('self'),ret=recordFor(SELF_RETURN,id),cap=capture('self',id),d=state.data||{};return{id:id||ret?.id||('self-'+Date.now()),mode:'SELF',startedAt:cap?.createdAt||ret?.updatedAt||new Date().toISOString(),endedAt:ret?.updatedAt||new Date().toISOString(),start:Number(d.intensity||ret?.start||0),end:Number(ret?.end||d.intensity||0),emotionChange:d.bodyChange||'',rule:d.rule||'',awareness:ret?.note||'',nextChoice:d.nextAction||''}}
function livePayload(){const state=read(LIVE_KEY,null);if(!state?.completed||!state?.pro?.completed)return null;const id=activeId('live'),ret=recordFor(LIVE_RETURN,id),cap=capture('live',id),obs=Object.values(state.pro.observations||{}),attempts=state.pro.attemptLog||[],lastObs=obs[obs.length-1]||{},lastAttempt=attempts[attempts.length-1]||{};return{id:id||ret?.id||('live-'+Date.now()),mode:'LIVE',startedAt:cap?.createdAt||lastAttempt.at||ret?.updatedAt||new Date().toISOString(),endedAt:ret?.updatedAt||lastAttempt.at||new Date().toISOString(),start:Number(ret?.start||0),end:Number(ret?.end||ret?.start||0),emotionChange:'',rule:RULES[lastObs.rule]||RULES[lastAttempt.innerRule]||'',awareness:ret?.note||'',nextChoice:lastAttempt.text||''}}
function payloadFor(mode){return mode==='SELF'?selfPayload():livePayload()}
function style(){if(document.getElementById('cfmSheetsStyle'))return;const s=document.createElement('style');s.id='cfmSheetsStyle';s.textContent='.cfm-sheet-share{margin:24px 0;padding:20px;border:1px solid rgba(220,255,69,.28);border-radius:18px;background:rgba(220,255,69,.045);color:#f7f4ec}.cfm-sheet-share h3{margin:5px 0 9px;font-size:clamp(20px,4vw,28px)}.cfm-sheet-share p{color:#c9c6be;line-height:1.65}.cfm-sheet-share ul{padding-left:20px;color:#dedbd2;line-height:1.65}.cfm-sheet-share details{margin:14px 0;padding:12px;border:1px solid rgba(255,255,255,.12);border-radius:14px}.cfm-sheet-share label{display:block;margin:10px 0;color:#eee}.cfm-sheet-share textarea{box-sizing:border-box;width:100%;min-height:74px;margin-top:6px;padding:11px;border:1px solid rgba(255,255,255,.18);border-radius:10px;background:#101214;color:#fff;font:inherit;line-height:1.55}.cfm-sheet-consent{display:flex!important;gap:9px;align-items:flex-start}.cfm-sheet-consent input{margin-top:5px}.cfm-sheet-share button{width:100%;padding:13px 16px;border:0;border-radius:12px;background:#dcff45;color:#10110d;font-weight:850;font-size:15px;cursor:pointer}.cfm-sheet-share button:disabled{opacity:.45;cursor:not-allowed}.cfm-sheet-status{min-height:24px;margin:10px 0 0!important;font-size:13px}.cfm-sheet-share.is-done{border-color:rgba(130,230,180,.45)}';document.head.appendChild(s)}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function create(mode,host){const data=payloadFor(mode);if(!data||sent()[data.id])return;const box=document.createElement('section');box.className='cfm-sheet-share';box.dataset.cfmSheetShare=mode;box.innerHTML='<small>ANONYMOUS LEARNING DATA</small><h3>비식별 기록을 자동 저장하고 있습니다.</h3><p>사람·장면·연락처·로그인 정보·기기 식별자는 전송하지 않습니다. 이메일·전화번호·링크·식별번호 형식은 전송 전에 자동으로 가립니다.</p><p class="cfm-sheet-status" aria-live="polite">운영 시트의 수신 확인을 기다리고 있습니다.</p>';host.appendChild(box);prepareAndSend(data,box,0)}
function prepareAndSend(data,box,attempt){data.rule=redact(data.rule);data.awareness=redact(data.awareness);data.nextChoice=redact(data.nextChoice);data.emotionChange=redact(data.emotionChange);data.schemaVersion=CONFIG.schemaVersion||'1.0';data.source=CONFIG.source||'coaching-flex-move';data.submissionId=data.submissionId||(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));sendAutomatically(data,box,attempt)}
async function sendAutomatically(data,box,attempt){const status=box.querySelector('.cfm-sheet-status');try{await fetch(CONFIG.endpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify(data)});const confirmed=await confirmReceipt(data.submissionId);if(!confirmed)throw new Error('receipt-timeout');markSent(data.id);box.classList.add('is-done');box.innerHTML='<small>AUTO SAVE COMPLETE</small><h3>비식별 기록이 자동 저장되었습니다.</h3><p>이번 훈련의 원문은 이 브라우저에 남고, 지정된 비식별 항목만 집계 시트에 기록되었습니다.</p>'}catch(e){console.error('[CFM sheets]',e);if(attempt<2){status.textContent='수신 확인이 지연되어 자동으로 다시 시도합니다.';setTimeout(()=>sendAutomatically(data,box,attempt+1),1200*(attempt+1));return}status.textContent='자동 저장을 확인하지 못했습니다. 브라우저 기록은 그대로 보존됩니다.';const retry=document.createElement('button');retry.type='button';retry.textContent='지금 다시 저장';retry.addEventListener('click',()=>{retry.remove();status.textContent='다시 전송하고 있습니다.';sendAutomatically(data,box,0)});box.appendChild(retry)}}
function confirmReceipt(id){return new Promise(resolve=>{let tries=0,done=false;const finish=v=>{if(done)return;done=true;resolve(v)};const check=()=>{if(++tries>6)return finish(false);const cb='__cfmReceipt'+Date.now()+Math.random().toString(36).slice(2);const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();setTimeout(check,650)},2200);const cleanup=()=>{clearTimeout(timer);delete window[cb];script.remove()};window[cb]=result=>{cleanup();if(result?.found)finish(true);else setTimeout(check,500)};script.onerror=()=>{cleanup();setTimeout(check,650)};script.src=CONFIG.endpoint+'?action=status&submissionId='+encodeURIComponent(id)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();document.head.appendChild(script)};setTimeout(check,500)})}
function inject(){queued=false;style();const self=document.querySelector('#selfFinal.active'),live=document.querySelector('#proFinal.active,#liveFinal.active,#professionalFinal.active');if(self&&!self.querySelector('[data-cfm-sheet-share]'))create('SELF',self.querySelector('#selfSummary')?.parentElement||self);if(live&&!live.querySelector('[data-cfm-sheet-share]'))create('LIVE',live.querySelector('#proSummary,#liveSummary,.summary-grid,.result-grid,.results-grid')?.parentElement||live)}
function schedule(){if(queued)return;queued=true;requestAnimationFrame(inject)}
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
})();
