const QUESTIONS=['이 직업은 사람을 직접 많이 만나나요?','주로 실내에서 일하나요?','결과물이 눈에 보이는 형태인가요?','안전이나 생명과 관련이 있나요?','컴퓨터나 기계를 자주 사용하나요?','팀으로 일하는 경우가 많나요?','전문 자격이나 교육이 꼭 필요한가요?','새로운 것을 만들거나 표현하나요?','현장 이동이 잦은 편인가요?','숫자나 자료를 많이 다루나요?','어린이나 청소년을 자주 만나나요?','고객에게 서비스를 직접 제공하나요?'];
const STORAGE_KEY='career-deduction-team-v4';
const state={phase:'setup',teamSizes:{A:5,B:5},teamNames:{A:'TEAM BLUE',B:'TEAM ORANGE'},players:{A:[],B:[]},rosters:{A:[],B:[]},revealed:{A:false,B:false},turn:'A',timerSeconds:30,bonusCount:3,bonusTurns:[3,6,9],bonusDone:[],turnCount:0,timeLeft:30,timer:null,bonusTimer:null,bonusTimeLeft:15,lastBonusType:null,pendingAction:null,log:[],winner:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=['setupScreen','dealScreen','playScreen','gameEndScreen'];
function showScreen(id){screens.forEach(x=>$('#'+x)?.classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'});}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function chosung(text){const CHO='ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ';return [...text].map(ch=>{const code=ch.charCodeAt(0)-44032;if(code>=0&&code<11172)return CHO[Math.floor(code/588)];return ch===' '?' ':(/[A-Za-z0-9·]/.test(ch)?ch:'');}).join('');}
function teamLabel(side){return state.teamNames[side]||`TEAM ${side}`;}
function opponent(side){return side==='A'?'B':'A';}
function clearTimers(){if(state.timer)clearInterval(state.timer);if(state.bonusTimer)clearInterval(state.bonusTimer);state.timer=null;state.bonusTimer=null;}
function save(){const copy={...state,timer:null,bonusTimer:null};localStorage.setItem(STORAGE_KEY,JSON.stringify(copy));}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(!x?.players?.A?.length||!x?.players?.B?.length)return false;Object.assign(state,x,{timer:null,bonusTimer:null});return true;}catch{return false;}}
function defaultPlayers(side,count){return Array.from({length:count},(_,i)=>({name:`${side==='A'?'블루':'오렌지'} ${i+1}`}));}
function renderTeamInputs(side){const box=$(`#names${side}`);if(!box)return;const count=state.teamSizes[side];const old=state.players[side]||[];const defaults=defaultPlayers(side,count);state.players[side]=Array.from({length:count},(_,i)=>old[i]||defaults[i]);box.innerHTML=state.players[side].map((p,i)=>`<label class="name-row"><span>${i+1}</span><input maxlength="12" value="${escapeHtml(p.name)}" aria-label="${teamLabel(side)} ${i+1}번 이름"></label>`).join('');$(`#count${side}`).textContent=count;}
function captureTeamInputs(side){const inputs=$$(`#names${side} input`);if(inputs.length)state.players[side]=inputs.map((el,i)=>({name:el.value.trim()||`${side==='A'?'블루':'오렌지'} ${i+1}`}));const nameInput=$(`#teamName${side}`);if(nameInput)state.teamNames[side]=nameInput.value.trim()||`TEAM ${side}`;}
function setTeamSize(side,next){captureTeamInputs(side);state.teamSizes[side]=Math.max(2,Math.min(6,next));renderTeamInputs(side);}
function initSetup(){state.players.A=defaultPlayers('A',5);state.players.B=defaultPlayers('B',5);renderTeamInputs('A');renderTeamInputs('B');$('#resumeBtn')?.classList.toggle('hidden',!localStorage.getItem(STORAGE_KEY));}
function collectSetup(){state.teamNames.A=$('#teamNameA').value.trim()||'TEAM BLUE';state.teamNames.B=$('#teamNameB').value.trim()||'TEAM ORANGE';state.players.A=$$('#namesA input').map((el,i)=>({name:el.value.trim()||`블루 ${i+1}`}));state.players.B=$$('#namesB input').map((el,i)=>({name:el.value.trim()||`오렌지 ${i+1}`}));state.teamSizes.A=state.players.A.length;state.teamSizes.B=state.players.B.length;state.timerSeconds=Number($('input[name="timer"]:checked').value);state.bonusCount=Number($('input[name="bonus"]:checked').value);prepareMatch();}
function calcBonusTurns(){return state.bonusCount===2?[4,8]:state.bonusCount===4?[3,5,7,9]:[3,6,9];}
function prepareMatch(){clearTimers();const jobs=shuffle(JOBS).slice(0,state.teamSizes.A+state.teamSizes.B);state.rosters.A=state.players.A.map((p,i)=>({player:p.name,job:jobs[i],revealed:false,scanned:false}));state.rosters.B=state.players.B.map((p,i)=>({player:p.name,job:jobs[state.teamSizes.A+i],revealed:false,scanned:false}));state.revealed={A:false,B:false};state.turn='A';state.turnCount=0;state.bonusTurns=calcBonusTurns();state.bonusDone=[];state.lastBonusType=null;state.log=[];state.winner=null;state.phase='deal';renderDeal();showScreen('dealScreen');save();}
function renderDeal(){$('#dealTeamA').textContent=`${teamLabel('A')} · ${state.teamSizes.A}명`;$('#dealTeamB').textContent=`${teamLabel('B')} · ${state.teamSizes.B}명`;$('#beginMatch').disabled=true;$('#beginMatch').textContent='두 팀 확인 후 배틀 시작';}
function renderSecretCards(side){return `<div class="secret-team-title ${side.toLowerCase()}"><b>${escapeHtml(teamLabel(side))}</b><span>${state.teamSizes[side]}개의 비밀 직업</span></div><div class="secret-card-grid">${state.rosters[side].map(x=>`<article class="secret-card ${side.toLowerCase()}"><small>${escapeHtml(x.player)} · ${x.job.id}</small><h3>${escapeHtml(x.job.name)}</h3><p>${escapeHtml(x.job.desc)}</p><div class="tags">${x.job.tags.map(t=>`<span class="tag">#${escapeHtml(t)}</span>`).join('')}</div></article>`).join('')}</div>`;}
function showTeamSecret(side){state.revealed[side]=true;$('#secretTitle').textContent=`${teamLabel(side)} 비밀 카드`;$('#secretContent').innerHTML=renderSecretCards(side);openModal('secretModal');if(state.revealed.A&&state.revealed.B){$('#beginMatch').disabled=false;$('#beginMatch').textContent='JOB BATTLE 시작 →';}save();}
