const QUESTIONS=['사람을 직접 많이 만나나요?','주로 실내에서 일하나요?','결과물이 눈에 보이는 형태인가요?','안전이나 생명과 관련이 있나요?','컴퓨터나 기계를 자주 사용하나요?','혼자보다 팀으로 일하는 경우가 많나요?','자격이나 전문 교육이 꼭 필요한가요?','새로운 것을 만들거나 표현하나요?','현장 이동이 잦은 편인가요?','숫자나 자료를 많이 다루나요?','어린이나 청소년을 자주 만나나요?','고객에게 서비스를 직접 제공하나요?'];
const ABILITIES={AGENT:[['비밀 조사','후보 직업 3개를 무작위로 확인하고 공개 소거하세요.'],['해시태그 공개','남아 있는 TEAM 전원이 자기 카드 해시태그 하나씩 공개합니다.'],['직업 급습','TEAM 한 명을 지정해 직업 하나를 즉시 추측합니다.']],TEAM:[['공동 조사','후보 직업 2개를 TEAM끼리 확인하고 공개 소거하세요.'],['해시태그 요청','AGENT가 자기 카드 해시태그 하나를 공개합니다.'],['직종 단서 요청','AGENT가 직종명을 말하지 않고 공통 특징 한 문장을 설명합니다.']]};
const state={phase:'setup',playerCount:5,players:[],round:1,totalRounds:5,agentIndex:0,timerSeconds:30,bonusCount:3,bonusGates:[4,8,11],bonusDone:[],agentJob:null,teamJobs:[],teamCategory:null,revealed:{agent:false,team:false},turn:'AGENT',positions:{AGENT:0,TEAM:0},scores:[],log:[],timer:null,timeLeft:30,pendingAction:null,portalStarter:null,bonusQuestion:null,bonusTimer:null,bonusTimeLeft:15,lastBonusType:null,lastRound:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens=['setupScreen','dealScreen','playScreen','roundEndScreen','gameEndScreen'];
function showScreen(id){screens.forEach(x=>$('#'+x).classList.toggle('hidden',x!==id));window.scrollTo({top:0,behavior:'smooth'});}
function shuffle(a){const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]];}return b;}
function pick(a){return a[Math.floor(Math.random()*a.length)];}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function chosung(text){const CHO='ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ';return [...text].map(ch=>{const code=ch.charCodeAt(0)-44032;if(code>=0&&code<11172)return CHO[Math.floor(code/588)];return ch===' '?' ':(/[A-Za-z0-9·]/.test(ch)?ch:'');}).join('');}
function save(){const copy={...state,timer:null,bonusTimer:null};localStorage.setItem('career-deduction-v2',JSON.stringify(copy));}
function load(){try{const x=JSON.parse(localStorage.getItem('career-deduction-v2'));if(!x||!x.players?.length)return false;Object.assign(state,x,{timer:null,bonusTimer:null});return true;}catch{return false;}}
function renderNameInputs(){const box=$('#nameInputs');box.innerHTML='';for(let i=0;i<state.playerCount;i++){const row=document.createElement('div');row.className='name-row';row.innerHTML=`<div class="avatar">${i+1}</div><input maxlength="12" value="${escapeHtml(state.players[i]?.name||`플레이어 ${i+1}`)}" aria-label="플레이어 ${i+1} 이름">`;box.appendChild(row);}$('#playerCountText').textContent=state.playerCount;}
function setPlayerCount(n){n=Math.max(3,Math.min(8,n));state.playerCount=n;renderNameInputs();}
function initSetup(){state.players=Array.from({length:5},(_,i)=>({name:`플레이어 ${i+1}`}));renderNameInputs();$('#resumeBtn').classList.toggle('hidden',!localStorage.getItem('career-deduction-v2'));}
function collectSetup(){const names=$$('#nameInputs input').map((el,i)=>el.value.trim()||`플레이어 ${i+1}`);state.players=names.map(name=>({name}));state.scores=names.map(()=>0);state.round=1;state.agentIndex=0;state.timerSeconds=Number($('input[name="timer"]:checked').value);state.bonusCount=Number($('input[name="bonus"]:checked').value);const mode=$('#roundMode').value;state.totalRounds=mode==='all'?state.playerCount:Number(mode);prepareRound();}
function calcBonusGates(){return state.bonusCount===2?[5,10]:state.bonusCount===4?[3,6,9,11]:[4,8,11];}
function prepareRound(){clearTimers();state.phase='deal';state.agentIndex=(state.round-1)%state.players.length;const cats=shuffle(Object.keys(CATEGORIES));state.teamCategory=cats[0];const teamPool=shuffle(JOBS.filter(j=>j.cat===state.teamCategory));const teamIndices=state.players.map((_,i)=>i).filter(i=>i!==state.agentIndex);state.teamJobs=teamIndices.map((playerIndex,i)=>({playerIndex,job:teamPool[i]}));const agentPool=JOBS.filter(j=>j.cat!==state.teamCategory);state.agentJob=pick(agentPool);state.revealed={agent:false,team:false};state.turn='AGENT';state.positions={AGENT:0,TEAM:0};state.bonusGates=calcBonusGates();state.bonusDone=[];state.lastBonusType=null;state.log=[];state.portalStarter=null;renderDeal();showScreen('dealScreen');save();}
function renderDeal(){const agent=state.players[state.agentIndex];$('#dealRoundBadge').textContent=`ROUND ${state.round} / ${state.totalRounds}`;$('#agentNameDeal').textContent=agent.name;$('#teamCountDeal').textContent=`TEAM ${state.players.length-1}명`;$('#beginRound').disabled=true;$('#beginRound').textContent='두 진영 확인 후 라운드 시작';}
function jobCardHtml(job,agent=false){return `<div class="secret-card ${agent?'agent':''}"><div class="code">${job.id} · ${CATEGORIES[job.cat].name}</div><h3>${escapeHtml(job.name)}</h3><p>${escapeHtml(job.desc)}</p><div class="tags">${job.tags.map(t=>`<span class="tag">#${escapeHtml(t)}</span>`).join('')}</div></div>`;}
function showAgentSecret(){state.revealed.agent=true;$('#secretEyebrow').textContent='AGENT SECRET';$('#secretTitle').textContent=`${state.players[state.agentIndex].name}의 직업`;$('#secretContent').innerHTML=jobCardHtml(state.agentJob,true);openModal('secretModal');checkDealReady();save();}
function showTeamSecret(){state.revealed.team=true;$('#secretEyebrow').textContent='TEAM SECRET';$('#secretTitle').textContent=`${CATEGORIES[state.teamCategory].name} 팀`;$('#secretContent').innerHTML=`<p class="micro">AGENT는 화면을 보지 마세요. TEAM은 아래 직업을 서로 공유합니다.</p><div class="team-cards">${state.teamJobs.map(x=>`<div class="team-mini"><small>${escapeHtml(state.players[x.playerIndex].name)} · ${x.job.id}</small><strong>${escapeHtml(x.job.name)}</strong><div class="tags" style="margin-top:8px">${x.job.tags.map(t=>`<span class="tag">#${escapeHtml(t)}</span>`).join('')}</div></div>`).join('')}</div>`;openModal('secretModal');checkDealReady();save();}
function checkDealReady(){if(state.revealed.agent&&state.revealed.team){$('#beginRound').disabled=false;$('#beginRound').textContent='라운드 시작 →';}}
