let feedbackCallback=null;
function openFeedback(type,title,message,buttonLabel,callback){clearTimers();feedbackCallback=typeof callback==='function'?callback:null;const card=$('#feedbackCard');card.classList.remove('correct','wrong');card.classList.add(type);$('#feedbackIcon').textContent=type==='correct'?'✓':'×';$('#feedbackKicker').textContent=type==='correct'?'NICE! PERFECT GUESS':'SO CLOSE! TRY AGAIN';$('#feedbackTitle').textContent=title;$('#feedbackMessage').textContent=message;$('#feedbackButton').textContent=buttonLabel||'확인 →';openModal('feedbackModal');setTimeout(()=>$('#feedbackButton').focus(),80);}
function confirmFeedback(){const callback=feedbackCallback;feedbackCallback=null;closeModal('feedbackModal');if(callback)callback();}
function openPortal(){clearTimers();$('#portalCopy').textContent=`${state.portalStarter}이(가) 먼저 포털에 도착했습니다. ${state.portalStarter}부터 최종 추측하고, 실제 결과에 맞춰 승자를 선택하세요.`;openModal('portalModal');}
function handlePortalResult(winner){if(winner==='DRAW'){closeModal('portalModal');state.positions.AGENT=11;state.positions.TEAM=11;state.turn=state.portalStarter==='AGENT'?'TEAM':'AGENT';log('최종 추측 모두 실패 · 11칸에서 서든데스 재개');renderTrack();renderTurn();startTurnTimer();return;}closeModal('portalModal');finishRound(winner,'portal');}
function finishRound(winner,method){clearTimers();state.phase='roundEnd';state.lastRound={winner,method};if(winner==='TEAM'){state.players.forEach((_,i)=>{if(i!==state.agentIndex)state.scores[i]+=10;});}else state.scores[state.agentIndex]+=20;save();renderRoundEnd(winner,method);showScreen('roundEndScreen');}
function renderRoundEnd(winner,method){$('#roundTrophy').textContent=winner==='TEAM'?'🔎':'🕵️';$('#roundEndEyebrow').textContent=`ROUND ${state.round} COMPLETE`;$('#roundEndTitle').textContent=`${winner} 승리!`;$('#roundEndCopy').textContent=method==='direct'?'포털 전에 정답을 맞혀 조기 승리!':'포털 최종 추측에서 승리!';$('#roundReveal').innerHTML=`<article class="panel role-card agent"><div><span class="role-label">AGENT ANSWER</span><h3>${escapeHtml(state.agentJob.name)}</h3><p>${escapeHtml(state.agentJob.desc)}</p></div><div class="tags">${state.agentJob.tags.map(t=>`<span class="tag">#${escapeHtml(t)}</span>`).join('')}</div></article><article class="panel role-card team"><div><span class="role-label">TEAM ANSWERS · ${CATEGORIES[state.teamCategory].name}</span><div class="team-cards" style="margin-top:18px">${state.teamJobs.map(x=>`<div class="team-mini"><small>${escapeHtml(state.players[x.playerIndex].name)}</small><strong>${escapeHtml(x.job.name)}</strong></div>`).join('')}</div></div></article>`;$('#nextRoundBtn').textContent=state.round>=state.totalRounds?'최종 순위 보기 →':'다음 라운드 →';}
function nextRound(){if(state.round>=state.totalRounds){renderGameEnd();showScreen('gameEndScreen');localStorage.removeItem('career-deduction-v2');return;}state.round++;prepareRound();}
function renderGameEnd(){state.phase='gameEnd';save();const ranking=state.players.map((p,i)=>({name:p.name,score:state.scores[i]})).sort((a,b)=>b.score-a.score);$('#finalRanking').innerHTML=ranking.map((x,i)=>`<div class="rank-row"><div class="rank-no">${i+1}</div><div><strong>${escapeHtml(x.name)}</strong><div class="micro">${i===0?'오늘의 JOB MASTER!':'끝까지 질문과 추리에 참여했어요.'}</div></div><div class="rank-score">${x.score}점</div></div>`).join('');}
function openModal(id){$('#'+id).classList.remove('hidden');document.body.style.overflow='hidden';}
function closeModal(id){$('#'+id).classList.add('hidden');if(!$$('.modal:not(.hidden)').length)document.body.style.overflow='';}
function resetAll(){clearTimers();if(confirm('현재 게임을 종료하고 처음 화면으로 돌아갈까요?')){localStorage.removeItem('career-deduction-v2');location.reload();}}

$('#minusPlayer').addEventListener('click',()=>setPlayerCount(state.playerCount-1));$('#plusPlayer').addEventListener('click',()=>setPlayerCount(state.playerCount+1));$('#startSetup').addEventListener('click',collectSetup);$('#showAgentCard').addEventListener('click',showAgentSecret);$('#showTeamCards').addEventListener('click',showTeamSecret);$('#beginRound').addEventListener('click',beginRound);$('#dealBack').addEventListener('click',()=>showScreen('setupScreen'));$('#completeAction').addEventListener('click',()=>completeMove(state.pendingAction==='ability'?'능력 사용':$('#actionTitle').textContent));$('#submitGuess').addEventListener('click',submitGuess);$('#feedbackButton').addEventListener('click',confirmFeedback);$('#revealBonus').addEventListener('click',revealBonus);$('#nextRoundBtn').addEventListener('click',nextRound);$('#resetBtn').addEventListener('click',resetAll);$('#newGame').addEventListener('click',()=>{localStorage.removeItem('career-deduction-v2');location.reload();});$('#restartSame').addEventListener('click',()=>{state.scores=state.players.map(()=>0);state.round=1;state.agentIndex=0;prepareRound();});
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.close;closeModal(id);if(state.phase==='play'&&(id==='actionModal'||id==='guessModal')&&!state.timer)startTurnTimer(false);}));$$('[data-action]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.action==='guess')openGuess();else actionPrompt(b.dataset.action);}));$$('[data-bonus-winner]').forEach(b=>b.addEventListener('click',()=>awardBonus(b.dataset.bonusWinner)));$$('[data-round-winner]').forEach(b=>b.addEventListener('click',()=>handlePortalResult(b.dataset.roundWinner)));
$('#resumeBtn').addEventListener('click',()=>{if(!load())return;state.playerCount=state.players.length;renderNameInputs();if(state.phase==='play'){renderPlay();showScreen('playScreen');startTurnTimer(false);}else if(state.phase==='roundEnd'&&state.lastRound){renderRoundEnd(state.lastRound.winner,state.lastRound.method);showScreen('roundEndScreen');}else if(state.phase==='gameEnd'){renderGameEnd();showScreen('gameEndScreen');}else{renderDeal();checkDealReady();showScreen('dealScreen');}});
window.addEventListener('keydown',event=>{if(event.key==='Enter'&&!$('#feedbackModal').classList.contains('hidden'))confirmFeedback();});
window.addEventListener('beforeunload',save);
initSetup();
