function beginMatch(){state.phase='play';renderPlay();showScreen('playScreen');startTurnTimer();save();}
function discovered(side){return state.rosters[opponent(side)].filter(x=>x.revealed).length;}
function remaining(side){return state.rosters[opponent(side)].filter(x=>!x.revealed).length;}
function renderPlay(){renderScoreboard();renderTargetBoards();renderBonusStatus();renderQuestions();renderLog();renderTurn();}
function renderScoreboard(){$('#scoreNameA').textContent=teamLabel('A');$('#scoreNameB').textContent=teamLabel('B');$('#scoreA').textContent=`${discovered('A')} / ${state.teamSizes.B}`;$('#scoreB').textContent=`${discovered('B')} / ${state.teamSizes.A}`;}
function targetCardHtml(entry,side,index){const status=entry.revealed?'revealed':entry.scanned?'scanned':'hidden-card';return `<article class="target-card ${side.toLowerCase()} ${status}"><div class="target-number">${index+1}</div><small>${escapeHtml(entry.player)}</small>${entry.revealed?`<strong>${escapeHtml(entry.job.name)}</strong><span>${CATEGORIES[entry.job.cat].name}</span>`:entry.scanned?`<strong>직종 스캔 완료</strong><span>${CATEGORIES[entry.job.cat].name}</span>`:`<strong>SECRET JOB</strong><span>질문으로 단서를 모아!</span>`}</article>`;}
function renderTargetBoards(){$('#targetTitleA').textContent=`${teamLabel('B')} 직업을 밝혀라!`;$('#targetTitleB').textContent=`${teamLabel('A')} 직업을 밝혀라!`;$('#remainingA').textContent=`${remaining('A')}개 남음`;$('#remainingB').textContent=`${remaining('B')}개 남음`;$('#targetBoardA').innerHTML=state.rosters.B.map((x,i)=>targetCardHtml(x,'A',i)).join('');$('#targetBoardB').innerHTML=state.rosters.A.map((x,i)=>targetCardHtml(x,'B',i)).join('');}
function renderBonusStatus(){$('#bonusStatus').innerHTML=state.bonusTurns.map((turn,i)=>`<span class="bonus-dot ${state.bonusDone.includes(turn)?'done':''}">${state.bonusDone.includes(turn)?'✓':i+1}</span>`).join('');}
function renderQuestions(){$('#questionBank').innerHTML=QUESTIONS.slice(0,8).map(q=>`<button class="question-chip" type="button">${escapeHtml(q)}</button>`).join('');$$('.question-chip').forEach(btn=>btn.addEventListener('click',()=>{navigator.clipboard?.writeText(btn.textContent);btn.textContent='복사됨 ✓';setTimeout(renderQuestions,700);}));}
function renderLog(){$('#gameLog').innerHTML=state.log.length?state.log.slice().reverse().map(x=>`<div class="log-item">${x}</div>`).join(''):`<div class="log-item">${escapeHtml(teamLabel('A'))}부터 배틀 시작!</div>`;}
function log(message){state.log.push(message);renderLog();save();}
function renderTurn(){const name=teamLabel(state.turn);$('#turnSideText').textContent=`${name} TURN`;$('#turnGuide').textContent=`상대 팀원 ${remaining(state.turn)}명의 직업이 남았습니다.`;$('#turnSpotlight').classList.toggle('orange-turn',state.turn==='B');$('#turnTimer').textContent=state.timeLeft||state.timerSeconds;}
function pauseTurnTimer(){if(state.timer)clearInterval(state.timer);state.timer=null;}
function startTurnTimer(reset=true){pauseTurnTimer();state.timeLeft=reset?state.timerSeconds:Math.max(1,state.timeLeft||state.timerSeconds);updateTurnTimer();state.timer=setInterval(()=>{state.timeLeft--;updateTurnTimer();if(state.timeLeft<=0){pauseTurnTimer();log(`<b>${escapeHtml(teamLabel(state.turn))}</b> 시간 종료`);advanceTurn();}},1000);}
function updateTurnTimer(){const timer=$('#turnTimer');timer.textContent=state.timeLeft;timer.classList.toggle('urgent',state.timeLeft<=5);}
function unresolvedTargets(side){return state.rosters[opponent(side)].map((entry,index)=>({...entry,index})).filter(x=>!x.revealed);}
function targetOptions(side){return unresolvedTargets(side).map(x=>`<option value="${x.index}">${escapeHtml(x.player)}${x.scanned?` · ${CATEGORIES[x.job.cat].name}`:''}</option>`).join('');}
function actionPrompt(type){pauseTurnTimer();state.pendingAction=type;const side=state.turn;const labels={clue:['🔍 단서 받기','선택한 상대 팀원이 자신의 직업과 관련된 도구·장소·대상·역량 중 하나만 말합니다.'],question:['❓ 질문하기','선택한 상대 팀원에게 예·아니오로 답할 수 있는 질문 하나만 합니다.'],ability:['⚡ 스캔 쓰기','선택한 상대 팀원의 직종을 즉시 공개합니다.']};const [title,body]=labels[type];$('#actionTitle').textContent=title;$('#actionContent').innerHTML=`<div class="field"><label for="actionTarget">상대 팀원 선택</label><select id="actionTarget">${targetOptions(side)}</select></div><div class="action-rule"><b>${body}</b><p>${type==='ability'?'직업명은 공개되지 않습니다.':'대답과 단서는 한 문장으로 짧게!'}</p></div>`;openModal('actionModal');}
function resolveAction(){const type=state.pendingAction;const targetIndex=Number($('#actionTarget')?.value);closeModal('actionModal');if(type==='ability'){const target=state.rosters[opponent(state.turn)][targetIndex];if(target&&!target.revealed){target.scanned=true;log(`<b>${escapeHtml(teamLabel(state.turn))}</b> 스캔! ${escapeHtml(target.player)}의 직종은 ${CATEGORIES[target.job.cat].name}`);renderTargetBoards();}}else{const target=state.rosters[opponent(state.turn)][targetIndex];log(`<b>${escapeHtml(teamLabel(state.turn))}</b> ${type==='clue'?'단서 요청':'질문'} → ${escapeHtml(target?.player||'상대 팀원')}`);}advanceTurn();}
function openGuess(){pauseTurnTimer();$('#guessTarget').innerHTML=targetOptions(state.turn);$('#guessJob').innerHTML=JOBS.map(j=>`<option value="${j.id}">${j.id} · ${escapeHtml(j.name)}</option>`).join('');openModal('guessModal');}
function submitGuess(){const side=state.turn;const targetIndex=Number($('#guessTarget').value);const target=state.rosters[opponent(side)][targetIndex];const guessedId=$('#guessJob').value;const guessed=JOBS.find(j=>j.id===guessedId);closeModal('guessModal');if(!target||target.revealed){startTurnTimer(false);return;}if(target.job.id===guessedId){openFeedback('correct','정답!',`“${target.player}”의 직업은 ${target.job.name}! 상대 직업 카드 1장을 공개합니다.`,'카드 공개 →',()=>{target.revealed=true;log(`<b>${escapeHtml(teamLabel(side))}</b> 정답! ${escapeHtml(target.player)} = ${escapeHtml(target.job.name)}`);renderScoreboard();renderTargetBoards();if(remaining(side)===0)finishMatch(side);else advanceTurn();});}else{openFeedback('wrong','아깝다!',`“${guessed?.name||guessedId}”은(는) ${target.player}의 직업이 아닙니다. 턴이 상대 팀으로 넘어갑니다.`,'턴 넘기기 →',()=>{log(`<b>${escapeHtml(teamLabel(side))}</b> 오답 · ${escapeHtml(target.player)} ≠ ${escapeHtml(guessed?.name||guessedId)}`);advanceTurn();});}}
function advanceTurn(){clearTimers();state.turnCount++;const gate=state.bonusTurns.find(x=>state.turnCount>=x&&!state.bonusDone.includes(x));if(gate){state.bonusDone.push(gate);renderBonusStatus();setTimeout(()=>launchBonus(gate),250);return;}toggleTurn();}
function toggleTurn(){state.turn=opponent(state.turn);renderTurn();startTurnTimer();save();}
function applyScan(side){const candidates=unresolvedTargets(side).filter(x=>!x.scanned);if(!candidates.length){log(`<b>${escapeHtml(teamLabel(side))}</b> 스캔 대상 없음`);return;}const chosen=pick(candidates);state.rosters[opponent(side)][chosen.index].scanned=true;log(`<b>${escapeHtml(teamLabel(side))}</b> 보너스 스캔! ${escapeHtml(chosen.player)} → ${CATEGORIES[chosen.job.cat].name}`);renderTargetBoards();}
function launchBonus(gate){clearTimers();state.bonusQuestion=makeBonusQuestion();$('#bonusType').textContent=state.bonusQuestion.type;$('#bonusQuestion').innerHTML=state.bonusQuestion.question;$('#bonusOptions').innerHTML=(state.bonusQuestion.options||[]).map((o,i)=>`<div class="bonus-option">${String.fromCharCode(65+i)}. ${escapeHtml(o)}</div>`).join('');$('#bonusAnswer').textContent=`정답: ${state.bonusQuestion.answer}`;$('#bonusAnswer').classList.add('hidden');$('#bonusAward').classList.add('hidden');$('#revealBonus').classList.remove('hidden');state.bonusTimeLeft=15;$('#bonusTimer').textContent='15초';openModal('bonusModal');state.bonusTimer=setInterval(()=>{state.bonusTimeLeft--;$('#bonusTimer').textContent=`${Math.max(0,state.bonusTimeLeft)}초`;if(state.bonusTimeLeft<=0){clearInterval(state.bonusTimer);state.bonusTimer=null;revealBonus();}},1000);log(`<b>BONUS ${gate}</b> 오픈!`);}
function makeBonusQuestion(){const job=pick(JOBS);const type=pick([0,1,2,3,4].filter(x=>x!==state.lastBonusType));state.lastBonusType=type;if(type===0)return{type:'초성 스피드',question:`<span style="color:var(--yellow)">${chosung(job.name)}</span><br><small>${CATEGORIES[job.cat].name}</small>`,answer:job.name};if(type===1)return{type:'해시태그 3',question:job.tags.map(t=>`#${escapeHtml(t)}`).join(' · '),answer:job.name};if(type===2){const others=shuffle(JOBS.filter(j=>j.cat===job.cat&&j.id!==job.id)).slice(0,3);const opts=shuffle([job,...others]);return{type:'한 줄 설명',question:escapeHtml(job.desc),options:opts.map(x=>x.name),answer:job.name};}if(type===3){const wrong=pick(Object.keys(CATEGORIES).filter(c=>c!==job.cat));const yes=Math.random()>.5;const cat=yes?job.cat:wrong;return{type:'직종 OX',question:`“${escapeHtml(job.name)}”은(는)<br><span style="color:var(--yellow)">${CATEGORIES[cat].name}</span> 직종이다.`,options:['O','X'],answer:yes?'O':'X'};}const cats=shuffle(Object.keys(CATEGORIES).filter(c=>c!==job.cat)).slice(0,3);const opts=shuffle([job.cat,...cats]);return{type:'직종 매치',question:escapeHtml(job.name),options:opts.map(c=>CATEGORIES[c].name),answer:CATEGORIES[job.cat].name};}
function revealBonus(){if(state.bonusTimer)clearInterval(state.bonusTimer);state.bonusTimer=null;$('#bonusAnswer').classList.remove('hidden');$('#bonusAward').classList.remove('hidden');$('#revealBonus').classList.add('hidden');}
function awardBonus(winner){closeModal('bonusModal');if(winner!=='NONE')applyScan(winner);else log('보너스 정답 팀 없음');toggleTurn();}
