function beginRound(){state.phase='play';renderPlay();showScreen('playScreen');startTurnTimer();save();}
function renderPlay(){$('#playRoundBadge').textContent=`ROUND ${state.round} / ${state.totalRounds}`;renderScoreboard();renderTrack();renderBonusStatus();renderQuestions();renderLog();renderTurn();}
function renderScoreboard(){const box=$('#scoreboard');box.innerHTML=state.players.map((p,i)=>`<div class="score-chip ${i===state.agentIndex?'agent':''}"><strong>${escapeHtml(p.name)}</strong><small>${i===state.agentIndex?'AGENT':'TEAM'}</small><span>${state.scores[i]||0}점</span></div>`).join('');}
function renderTrack(){const gates=new Set(state.bonusGates);$('#track').innerHTML=['AGENT','TEAM'].map(side=>`<div class="track-row"><div class="track-name ${side.toLowerCase()}">${side}</div><div class="track-cells">${Array.from({length:12},(_,i)=>{const n=i+1;return `<div class="cell ${gates.has(n)?'gate':''} ${state.positions[side]===n?'on '+side.toLowerCase():''}">${state.positions[side]===n?'●':n}</div>`}).join('')}</div><div class="track-score">${state.positions[side]}/12</div></div>`).join('');}
function renderBonusStatus(){$('#bonusStatus').innerHTML=state.bonusGates.map((g,i)=>`<div class="bonus-gate ${state.bonusDone.includes(g)?'done':''}"><strong>GATE ${i+1}</strong><br>${g}칸 ${state.bonusDone.includes(g)?'완료':'대기'}</div>`).join('');}
function renderQuestions(){$('#questionBank').innerHTML=QUESTIONS.slice(0,8).map(q=>`<button class="question-chip" type="button">${escapeHtml(q)}</button>`).join('');$$('.question-chip').forEach(btn=>btn.addEventListener('click',()=>{navigator.clipboard?.writeText(btn.textContent);btn.textContent='복사됨 ✓';setTimeout(()=>renderQuestions(),700);}));}
function renderLog(){const box=$('#gameLog');box.innerHTML=state.log.length?state.log.slice().reverse().map(x=>`<div class="log-item">${x}</div>`).join(''):'<div class="log-item">라운드가 시작되었습니다. AGENT가 먼저 움직입니다.</div>';}
function log(msg){state.log.push(msg);renderLog();save();}
function renderTurn(){const side=state.turn;$('#turnSideText').textContent=`${side} TURN`;$('#turnGuide').textContent=side==='AGENT'?`${state.players[state.agentIndex].name}, TEAM의 직업을 좁히세요.`:'TEAM, AGENT의 직업을 함께 추리하세요.';$('#turnTimer').textContent=state.timeLeft||state.timerSeconds;}
function clearTimers(){if(state.timer)clearInterval(state.timer);if(state.bonusTimer)clearInterval(state.bonusTimer);state.timer=null;state.bonusTimer=null;}
function pauseTurnTimer(){if(state.timer)clearInterval(state.timer);state.timer=null;}
function startTurnTimer(reset=true){if(state.timer)clearInterval(state.timer);state.timeLeft=reset?state.timerSeconds:Math.max(1,state.timeLeft||state.timerSeconds);updateTurnTimer();state.timer=setInterval(()=>{state.timeLeft--;updateTurnTimer();if(state.timeLeft<=0){clearInterval(state.timer);state.timer=null;log(`<b>${state.turn}</b> 시간 종료 · 자동으로 1칸 이동`);completeMove('시간 종료');}},1000);}
function updateTurnTimer(){const t=$('#turnTimer');t.textContent=state.timeLeft;t.classList.toggle('urgent',state.timeLeft<=5);}
function actionPrompt(type){pauseTurnTimer();const side=state.turn;const data={clue:{title:'간접 단서 요청',body:side==='AGENT'?'TEAM 한 명을 지정해, 그 직업의 도구·대상·장소·필요 역량 중 하나를 한 문장으로 듣습니다.':'AGENT가 자기 직업의 도구·대상·장소·필요 역량 중 하나를 한 문장으로 설명합니다.'},question:{title:'예·아니오 질문',body:'직업명을 직접 말하지 않고 질문 하나만 합니다. 답은 “예 / 아니오 / 상황에 따라 달라요” 중 하나입니다.'},ability:{title:'능력 사용',body:''}}[type];state.pendingAction=type;$('#actionTitle').textContent=data.title;if(type==='ability'){const a=pick(ABILITIES[side]);$('#actionContent').innerHTML=`<h3>${a[0]}</h3><p class="ability-result">${a[1]}</p><p class="micro">효과를 실행한 뒤 완료 버튼을 누르세요.</p>`;}else{$('#actionContent').innerHTML=`<h3>${data.title}</h3><p>${data.body}</p><p class="prompt">${state.timerSeconds}초 안에 한 번만 실행하세요.</p>`;}openModal('actionModal');}
function openGuess(){pauseTurnTimer();const side=state.turn;$('#guessTitle').textContent=side==='TEAM'?'AGENT의 직업 추측':'TEAM 직업 급습';$('#targetField').classList.toggle('hidden',side==='TEAM');if(side==='AGENT'){$('#guessTarget').innerHTML=state.teamJobs.map(x=>`<option value="${x.playerIndex}">${escapeHtml(state.players[x.playerIndex].name)}</option>`).join('');}$('#guessJob').innerHTML=JOBS.map(j=>`<option value="${j.id}">${j.id} · ${escapeHtml(j.name)}</option>`).join('');openModal('guessModal');}
function submitGuess(){const side=state.turn;const id=$('#guessJob').value;let correct=false;if(side==='TEAM'){correct=state.agentJob.id===id;}else{const target=Number($('#guessTarget').value);const entry=state.teamJobs.find(x=>x.playerIndex===target);correct=entry?.job.id===id;}closeModal('guessModal');const guessed=JOBS.find(j=>j.id===id)?.name||id;if(correct){log(`<b>${side}</b> 정답! “${escapeHtml(guessed)}”`);finishRound(side,'direct');}else{log(`<b>${side}</b> 오답 “${escapeHtml(guessed)}” · 정답은 아직 비밀`);completeMove('오답 추측');}}
function completeMove(label){closeModal('actionModal');clearTimers();const side=state.turn;state.positions[side]=Math.min(12,state.positions[side]+1);log(`<b>${side}</b> ${escapeHtml(label)} · ${state.positions[side]}칸`);renderTrack();const gate=state.bonusGates.find(g=>state.positions[side]>=g&&!state.bonusDone.includes(g));if(gate){state.bonusDone.push(gate);renderBonusStatus();setTimeout(()=>launchBonus(gate),350);return;}if(state.positions[side]>=12){state.portalStarter=side;setTimeout(openPortal,350);return;}toggleTurn();}
function toggleTurn(){state.turn=state.turn==='AGENT'?'TEAM':'AGENT';renderTurn();startTurnTimer();save();}
function launchBonus(gate){clearTimers();state.bonusQuestion=makeBonusQuestion();$('#bonusType').textContent=state.bonusQuestion.type;$('#bonusQuestion').innerHTML=state.bonusQuestion.question;$('#bonusOptions').innerHTML=(state.bonusQuestion.options||[]).map((o,i)=>`<div class="bonus-option">${String.fromCharCode(65+i)}. ${escapeHtml(o)}</div>`).join('');$('#bonusAnswer').textContent=`정답: ${state.bonusQuestion.answer}`;$('#bonusAnswer').classList.add('hidden');$('#bonusAward').classList.add('hidden');$('#revealBonus').classList.remove('hidden');state.bonusTimeLeft=15;$('#bonusTimer').textContent='15초';openModal('bonusModal');state.bonusTimer=setInterval(()=>{state.bonusTimeLeft--;$('#bonusTimer').textContent=`${Math.max(0,state.bonusTimeLeft)}초`;if(state.bonusTimeLeft<=0){clearInterval(state.bonusTimer);state.bonusTimer=null;revealBonus();}},1000);log(`<b>BONUS GATE ${gate}</b> 시작`);}
function makeBonusQuestion(){const job=pick(JOBS);const type=Math.floor(Math.random()*5);if(type===0)return{type:'초성 스피드',question:`<span style="color:var(--yellow)">${chosung(job.name)}</span><br><small style="font-size:.42em;color:rgba(255,255,255,.65)">${CATEGORIES[job.cat].name}</small>`,answer:job.name};if(type===1)return{type:'해시태그 3',question:job.tags.map(t=>`#${escapeHtml(t)}`).join(' · '),answer:job.name};if(type===2){const others=shuffle(JOBS.filter(j=>j.id!==job.id)).slice(0,3);const opts=shuffle([job,...others]);return{type:'한 줄 설명',question:escapeHtml(job.desc),options:opts.map(x=>x.name),answer:job.name};}if(type===3){const wrong=pick(Object.keys(CATEGORIES).filter(c=>c!==job.cat));const trueStatement=Math.random()>.5;const cat=trueStatement?job.cat:wrong;return{type:'직종 OX',question:`“${escapeHtml(job.name)}”은(는)<br><span style="color:var(--yellow)">${CATEGORIES[cat].name}</span> 직종이다.`,options:['O','X'],answer:trueStatement?'O':'X'};}const cats=shuffle(Object.keys(CATEGORIES).filter(c=>c!==job.cat)).slice(0,3);const opts=shuffle([job.cat,...cats]);return{type:'직종 매치',question:`${escapeHtml(job.name)}`,options:opts.map(c=>CATEGORIES[c].name),answer:CATEGORIES[job.cat].name};}
function revealBonus(){if(state.bonusTimer)clearInterval(state.bonusTimer);state.bonusTimer=null;$('#bonusAnswer').classList.remove('hidden');$('#bonusAward').classList.remove('hidden');$('#revealBonus').classList.add('hidden');}
function awardBonus(winner){closeModal('bonusModal');if(winner!=='NONE'){state.positions[winner]=Math.min(12,state.positions[winner]+1);log(`<b>${winner}</b> 보너스 정답 · 부스터 +1칸`);renderTrack();if(state.positions[winner]>=12){state.portalStarter=winner;setTimeout(openPortal,300);return;}}else log('보너스 정답 진영 없음');toggleTurn();}
